sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-itcast0820
    access-key-id: LTAI5tCZCoXqqterKYZfFUqc
    access-key-secret: MzhH5EedGKxo6AIRfmo33uA2X304mt

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx2cb06c9c15d9621f
    secret: 17d5d7901fc0a89010d025ae02ae0853
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://3cd67fd5.r12.cpolar.top/notify/paySucess
    refundNotifyUrl: https://3cd67fd5.r12.cpolar.top/notify/refundSuccess
